services:
  - type: web
    name: line-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.api.webhook:app
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: GOOGLE_SHEETS_CREDENTIALS
        sync: false
      - key: GOOGLE_SHEETS_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false 